// Writes docs/ANSWER-RULES.md: every word whose typed answer is graded leniently, and what it accepts.
// Generated from site/js/answer-rules.js and the word list, so it always matches what the quiz does.
// A unit test fails if the committed file is out of date.
//
// Usage: npm run docs:rules
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { RULES, TOPIC_RULES, answerVariants } from "../site/js/answer-rules.js";
import { acceptedAnswers } from "../site/js/quiz.js";
import { TOPICS } from "../site/js/vocab.js";

export const OUT_FILE = resolve(dirname(fileURLToPath(import.meta.url)), "../docs/ANSWER-RULES.md");

export function renderTable(topics = TOPICS) {
  const lines = [
    "# Lenient typed answers",
    "",
    "<!-- Generated by scripts/answer_rules_table.js (npm run docs:rules). Do not edit by hand. -->",
    "",
    "What each word accepts in the quiz's typed questions, beyond the exact textbook answer. Rules are defined and turned on per topic in `site/js/answer-rules.js`. Topics not listed here are graded exactly. Multiple choice is never affected.",
  ];
  for (const topic of topics) {
    const config = TOPIC_RULES[topic.id];
    if (!config) continue;
    const variants = answerVariants(topic.id);
    const lenient = [];
    const exact = [];
    for (const word of topic.words) {
      const extra = acceptedAnswers(word, topic.words, variants).filter((a) => a !== word.chinese);
      if (extra.length) {
        lenient.push(`| ${word.chinese} | ${word.english} | ${extra.join(", ")} |`);
        continue;
      }
      // Words a rule is about but leaves exact, and why.
      for (const { rule, except = [] } of config) {
        const result = RULES[rule].apply(word.chinese);
        if (!result) continue;
        const reason = except.includes(word.chinese) ? "excluded by the teacher" : (result.skip ?? "would match another word in this topic");
        exact.push(`| ${word.chinese} | ${word.english} | ${reason} |`);
        break;
      }
    }
    lines.push("", `## ${topic.name} (\`${topic.id}\`)`, "", `Rules: ${config.map((c) => `\`${c.rule}\``).join(", ")}`);
    lines.push("", "### Also accepts other spellings", "", "| Word | English | Also accepted |", "|---|---|---|", ...lenient);
    lines.push("", "### Exact only: the rule deliberately doesn't apply", "", "| Word | English | Why |", "|---|---|---|", ...exact);
    lines.push("", `All other ${topic.name} words are graded exactly too. The rule isn't about them.`);
  }
  return lines.join("\n") + "\n";
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync(OUT_FILE, renderTable());
  console.log(`Wrote ${OUT_FILE}`);
}
