"""Convert Knowt flashcard PDF exports in data/source/ into data/vocab.csv and site/js/vocab.js.

Each PDF is one topic. Files are processed in filename order (e.g. 01-school.pdf).
The topic's ID for links comes from the file name ("school"), and its display name
from the PDF title (e.g. "School 学校").

Usage: python3 scripts/pdf_to_csv.py
Requires poppler-utils (pdftotext, pdfinfo).
"""
import csv
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "data" / "source"
OUT_FILE = ROOT / "data" / "vocab.csv"
JS_FILE = ROOT / "site" / "js" / "vocab.js"

# Teacher-approved corrections to the source sets: (topic, chinese) -> english.
OVERRIDES = {
    ("School 学校", "电脑"): "computer",
}

# A card row: Chinese term, a wide gap, then the English definition.
ROW = re.compile(r"^\s*(\S.*?)\s{2,}(\S.*?)\s*$")
HAS_CJK = re.compile(r"[一-鿿]")


def pdf_title(path):
    info = subprocess.run(["pdfinfo", str(path)], capture_output=True, text=True, check=True).stdout
    for line in info.splitlines():
        if line.startswith("Title:"):
            return line.split(":", 1)[1].strip()
    return path.stem


def topic_id(path):
    # The stable ID used in links: "01-school.pdf" -> "school". The number prefix only sets the order.
    topic = re.sub(r"^\d+[-_ ]*", "", path.stem).lower()
    topic = re.sub(r"[^a-z0-9]+", "-", topic).strip("-")
    if not topic:
        sys.exit(f"{path.name}: file name needs a topic after the number, e.g. 02-family.pdf")
    return topic


def normalize_english(text):
    # "grade;score" and "grade; score" should display the same way.
    return re.sub(r"\s*;\s*", "; ", text)


def parse_pdf(path, topic):
    text = subprocess.run(["pdftotext", "-layout", str(path), "-"], capture_output=True, text=True, check=True).stdout
    rows = []
    for line in text.splitlines():
        if not line.strip() or "knowt.com" in line or line.strip() == topic:
            continue
        match = ROW.match(line)
        if not match:
            continue
        chinese, english = match.groups()
        # Skip the page header ("10/9/26, 6:50 PM   School 学校"): its left side has no Chinese.
        if not HAS_CJK.search(chinese):
            continue
        english = OVERRIDES.get((topic, chinese), normalize_english(english))
        rows.append((chinese, english))
    return rows


def main():
    pdfs = sorted(SOURCE_DIR.glob("*.pdf"))
    if not pdfs:
        sys.exit(f"No PDFs found in {SOURCE_DIR}")
    topics = []
    with OUT_FILE.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["topic", "chinese", "english"])
        for pdf in pdfs:
            topic = pdf_title(pdf)
            rows = parse_pdf(pdf, topic)
            for chinese, english in rows:
                writer.writerow([topic, chinese, english])
            topics.append({"id": topic_id(pdf), "name": topic, "words": [{"chinese": c, "english": e} for c, e in rows]})
            print(f"{pdf.name}: {topic!r} -> {len(rows)} words")
    JS_FILE.parent.mkdir(parents=True, exist_ok=True)
    JS_FILE.write_text(
        "// Generated by scripts/pdf_to_csv.py. Do not edit by hand.\n"
        f"export const TOPICS = {json.dumps(topics, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT_FILE.relative_to(ROOT)} and {JS_FILE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
